services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: nextcrm_db
    environment:
      POSTGRES_DB: nextcrm
      POSTGRES_USER: nextcrm_user
      POSTGRES_PASSWORD: nextcrm_password_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: >
      postgres -c listen_addresses='*'
      -c shared_preload_libraries='pg_stat_statements'
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

volumes:
  postgres_data:
    driver: local